{
  "handler": "exception",
  "success": true,
  "timeout": 2000,
  "expect": {
    "to.deep.equal()": {
      "statusCode": 500,
      "body": "{\"message\":\"Internal Server Error\"}"
    }
  },
  "logs": {
    "to.deep.equal()": [
      "WARNING: Some Exception: GET exception\n{\"context\":\"lambda-serverless-api\",\"route\":\"GET exception\",\"error\":{\"name\":\"Error\",\"message\":\"Some Exception\",\"stack\":\"Error: Some Exception\\n    at file://<root>/test/handler.js?id=<seed>:62:9\\n    at Array.<anonymous> (file://<root>/src/logic/api-gateway.js?id=<seed>:81:14)\\n    at async file://<root>/src/logic/api-gateway.js?id=<seed>:99:25\"}}"
    ]
  },
  "event": {
    "httpMethod": "GET",
    "headers": {
      "X-api-version": "1.0.1"
    },
    "requestContext": {
      "identity": {
        "sourceIp": "127.0.0.1"
      }
    }
  }
}
